spring:
  application:
    name: demo
  datasource:
    url: jdbc:mariadb://localhost:3333/labdb
    username: andrey
    password: ${DB_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: 3600000000000

# SendGrid
key: ${SENDGRID_KEY:sendgrid}

# Paypal
paypal:
  client:
    id: ${ID_PAYPAL}
    secret: ${SECRET_KEY_PAYPAL}
  mode: sandbox