spring:
  application:
    name: demo
  datasource:
    url: jdbc:mariadb://localhost:3333/labdb
    username: andrey
    password: password123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000000000

# SendGrid
key: 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

# Paypal
paypal:
  client:
    id: Ad7pr-QycJFpHCa6IIbCxfr58VVflaGSUgXEhc8WgggP2r3ednQS2C0yu_WnIuSBcXvKC8J3zFq7iRKS
    secret: EFy4id_DXLLvC7L04YCkp8IQFza10Cu8xbro0zIQ6uYbqB8rJFKF4TI12XrEDqriEFbdaihxj6_73q9k
  mode: sandbox